version: "3.3"



services:
  eval_backend:
    build: src
    image: eval_backend
    container_name: eval_backend
    ports:
      - 8002:5000

    environment:
      YPATH: /test_y.csv

    volumes:
      - ./test_y2020.csv:/test_y.csv
      - ./src/logs:/src/logs